name: movie_recommender
description: Application which helps choosing movies basing on user's preferences.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_storage: ^11.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.2.14
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  optimized_cached_image: ^3.0.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: 'assets/icon.png'

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/